# Site/SEO settings
email: nicho101002@gmail.com
baseurl: ""
permalink: /:year/:month/:day/:title/
google_analytics: 

name: Nicholaus Suprapto
title: Nicholaus' Thoughts
description: >
  Welcome to my personal blog. I write my random thoughts and post them here.
url: http://ininicho.github.io/ininicho.github.io
twitter_username: ininicho_
default_img: /assets/images/seo.jpg
social:
  - name: twitter
    url: https://twitter.com/ininicho_
  - name: instagram
    url: https://www.instagram.com/ininicho_/
  - name: linkedin
    url: https://www.linkedin.com/in/nicholaus-suprapto-73abb8190/
  - name: github
    url: https://github.com/ininicho

# Contact settings
contact_img: /assets/images/placeholder-28.jpg
formcarry: https://formcarry.com/s/A0mNJbiQxS1j

# Disqus settings
disqus: ininicho-github-io

# MailChimp settings
mailchimp_action: https://app.us17.list-manage.com/subscribe/post?u=e6c8689ed92ff943420d4072d&amp;id=ef8453e92a
mailchimp_input: 8e0a97b37a6ec357944ecdb422b327d0-us17

# Author settings
author:
  - name: Nicholaus Suprapto
    bio: Born Indonesian. Currently a freshman at University of Waterloo studying Mathematics. Tech enthusiast and food lover. 
    url: http://github.com/ininicho

# Pagination settings
pagination:
  enabled: true
  debug: false
  per_page: 2
  permalink: '/page/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    layouts: 
      - 'tag.html'
    title: 'The Barber Theme'
    permalink: '/tag/:tag'
    slugify:
      mode: raw
      cased: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
  - vendor
